### ISSUE TITLE
Add a script to output a list of properties where the taxes are higher than the property value.

### ISSUE THREAD

**Issue by DavidEBest** [codefordayton/scrapers#26]
Based on the conversation with Preservation Dayton at the December meeting, we need to capture all the properties all the properties where the taxes owed are higher than the properties assessed value. This can be done from the delinquent properties csv that is saved in this repo.

The relevant fields in the CSV are `ASMTTOTAL` (100% Appraised Total Value) and  `NETDELQ` (Net delinquent Amount).

The first pass output from this should contain all the fields in the existing CSV file, but only the record where `NETDELQ` is greater than `ASMTTOTAL`. The file should be saved in the local directory so it can be processed via the scrape command.

**Comment by musebc** [comment]
@DavidEBest I don't see the CSV checked into the repo. Is there a script that we're expecting to be run before the parser to download the file?

**Comment by DavidEBest** [comment]
Sorry about that... I actually gitignore those files.

The scraper itself downloads them at the beginning of the process. You can grab the latest file from [here](http://www.mctreas.org/mctreas/fdpopup.cfm?dtype=DQ).
